twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        api_key: '%env(API_KEY)%'
        navbar: true
        label:
            app_name: 'Travel Planner'

when@test:
    twig:
        strict_variables: true
